tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

  - name: postgres
    init: |
      docker-compose up -d

  - name: Install PostgreSQL Client
    init: |
      sudo apt-get update
      sudo apt-get install -y postgresql-client    

  - name: react-js
    command: |
      cd frontend-react-js
      npm i

  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt

  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb    
      cd backend-flask
      
  - name: rails
    init: |
      source /home/gitpod/.rvm/scripts/rvm
      rvm install "ruby-3.2.2"
      rvm use "ruby-3.2.2" --default
      gem update --system
      gem install rails  
      echo 'export PATH="$PATH:$(ruby -e "puts Gem.user_dir")/bin"' >> ~/.bashrc
      cd cruddur
      bundle install
      rails db:create
      rails db:migrate
      rails db:seed

ports:
  - name: frontend
    port: 3000-3100
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
