tasks:
  - init: |
      # Update RubyGems
      gem update --system 3.5.5

      # Install Rails (this assumes Ruby is already installed)
      gem install rails 

      # Cache the installation of gems to speed up future workspace startups
      # Optional: Specify the path to cache
