tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"

  - name: react-js
    command: |
      cd frontend-react-js
      npm i

  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt

  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb    
      cd backend-flask
      
  - name: rails
    init: |
       # Source RVM scripts
       source /home/gitpod/.rvm/scripts/rvm
   
       # Install and use a specific Ruby version
       rvm install "ruby-3.2.2"
       rvm use "ruby-3.2.2" --default
     
       # Update RubyGems
       gem update --system
   
       # Install Rails
       gem install rails  
   
       # Append Gem bin directory to PATH (for the current session)
       export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"

       # Change to the root directory of the Rails application
       cd cruddur

       # Install all gems specified in Gemfile
       bundle install

      # Cache the installation of gems to speed up future workspace startups
      # Optional: Specify the path to cache
ports:
  - name: frontend
    port: 3000-3100
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
