# Week 1           : App Containerization
# Cloud Boot-Camper: Utra Man (Tony)
#
# Configurations for Backend
#
#

FROM python:3.10-slim-buster
# FROM 875250894678.dkr.ecr.us-west-1.amazonaws.com/cruddur-python:3.10-slim-buster


# Inside Container
# make a new folder inside container
WORKDIR /backend-flask

# Outside Container -> Inside Container
# this contains the libraries want to install to run the app
COPY requirements.txt requirements.txt

# Inside Container
# Install the python libraries used for the app
RUN pip3 install -r requirements.txt

# Outside Container -> Inside Container
# . means everything in the current directory
# first period . - /backend-flask (outside container)
# second period . /backend-flask (inside container)
COPY . .

# Set Enviroment Variables (Env Vars)
# Inside Container and wil remain set when the container is running
ENV FLASK_DEBUG=1

EXPOSE ${PORT}

# python3 -m flask run --host=0.0.0.0 --port=4567
#ENV PYTHONUNBUFFERED=1
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]
